databases:
  - name: oshiconnect-db
    plan: free
    databaseName: oshiconnect
    user: oshiconnect

services:
  - type: web
    name: oshiconnect
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oshiconnect-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
